
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symT {
  /* terminals */
  public static final int INITC = 65;
  public static final int CANT_ACIERTOS = 98;
  public static final int LETIMPAR = 56;
  public static final int BARRA = 5;
  public static final int H1 = 23;
  public static final int TYPE = 34;
  public static final int ROWS = 38;
  public static final int IDET = 101;
  public static final int ASC = 53;
  public static final int NAME = 36;
  public static final int FFAMILY = 32;
  public static final int MAYIG = 77;
  public static final int DATOS_FORM = 26;
  public static final int CORCHCUADI = 6;
  public static final int ALT = 43;
  public static final int ONLOAD = 89;
  public static final int CORCHCUADD = 7;
  public static final int CARALEATORIO = 58;
  public static final int INTEGER = 48;
  public static final int DIFER = 79;
  public static final int FALSE = 74;
  public static final int ALERTINFO = 60;
  public static final int PROCESO = 90;
  public static final int ELSEIF = 67;
  public static final int THENWHILE = 63;
  public static final int THEN = 64;
  public static final int GETELEMENT = 91;
  public static final int PARI = 84;
  public static final int WIDTH = 41;
  public static final int REVERSE = 57;
  public static final int PARD = 85;
  public static final int CLASS = 39;
  public static final int CANT_USOS = 97;
  public static final int BACK = 29;
  public static final int SELECT = 17;
  public static final int TEXTAREA = 16;
  public static final int REDIRECT = 104;
  public static final int COMA = 92;
  public static final int HUNTIL = 70;
  public static final int VALP = 47;
  public static final int DOBIGUAL = 78;
  public static final int TRUE = 73;
  public static final int IGUAL = 8;
  public static final int WHILE = 72;
  public static final int COLS = 37;
  public static final int PAR = 24;
  public static final int DECIMAL = 49;
  public static final int CHAR = 51;
  public static final int BOOLEAN = 50;
  public static final int LETPAR = 55;
  public static final int TEXTALIGN = 33;
  public static final int INPUT = 15;
  public static final int GCIC = 9;
  public static final int ULTIMA_FECHA = 100;
  public static final int MAY = 2;
  public static final int DIV = 19;
  public static final int PALABRAS = 46;
  public static final int MULT = 83;
  public static final int ELSE = 68;
  public static final int PALABRA = 45;
  public static final int NUMALEA = 59;
  public static final int CORCHI = 87;
  public static final int NOMBRE_CAP = 96;
  public static final int MENIG = 76;
  public static final int DECIM = 102;
  public static final int CORCHD = 88;
  public static final int LINK = 12;
  public static final int EOF = 0;
  public static final int SUMA = 81;
  public static final int BUTTON = 22;
  public static final int CARACTER = 103;
  public static final int CANT_FALLOS = 99;
  public static final int REPEAT = 69;
  public static final int SPAM = 14;
  public static final int FSIZE = 31;
  public static final int SCRIPTING = 25;
  public static final int SRC = 40;
  public static final int BODY = 13;
  public static final int HREF = 28;
  public static final int TITLE = 11;
  public static final int OR = 80;
  public static final int error = 1;
  public static final int EXIT = 61;
  public static final int RESTA = 82;
  public static final int EXCL = 4;
  public static final int IF = 62;
  public static final int DESC = 54;
  public static final int COLOR = 30;
  public static final int HEAD = 10;
  public static final int END = 66;
  public static final int IMG = 20;
  public static final int DOSPUNT = 94;
  public static final int HEIGHT = 42;
  public static final int BR = 21;
  public static final int FDATOS_FORM = 27;
  public static final int GLOBAL = 75;
  public static final int OPTION = 18;
  public static final int INSERT = 71;
  public static final int PUNTCOMA = 86;
  public static final int STRING = 52;
  public static final int ONCLICK = 44;
  public static final int AND = 93;
  public static final int ID_CAP = 95;
  public static final int IDETIQUETA = 35;
  public static final int MEN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAY",
  "MEN",
  "EXCL",
  "BARRA",
  "CORCHCUADI",
  "CORCHCUADD",
  "IGUAL",
  "GCIC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "H1",
  "PAR",
  "SCRIPTING",
  "DATOS_FORM",
  "FDATOS_FORM",
  "HREF",
  "BACK",
  "COLOR",
  "FSIZE",
  "FFAMILY",
  "TEXTALIGN",
  "TYPE",
  "IDETIQUETA",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "PALABRA",
  "PALABRAS",
  "VALP",
  "INTEGER",
  "DECIMAL",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "ASC",
  "DESC",
  "LETPAR",
  "LETIMPAR",
  "REVERSE",
  "CARALEATORIO",
  "NUMALEA",
  "ALERTINFO",
  "EXIT",
  "IF",
  "THENWHILE",
  "THEN",
  "INITC",
  "END",
  "ELSEIF",
  "ELSE",
  "REPEAT",
  "HUNTIL",
  "INSERT",
  "WHILE",
  "TRUE",
  "FALSE",
  "GLOBAL",
  "MENIG",
  "MAYIG",
  "DOBIGUAL",
  "DIFER",
  "OR",
  "SUMA",
  "RESTA",
  "MULT",
  "PARI",
  "PARD",
  "PUNTCOMA",
  "CORCHI",
  "CORCHD",
  "ONLOAD",
  "PROCESO",
  "GETELEMENT",
  "COMA",
  "AND",
  "DOSPUNT",
  "ID_CAP",
  "NOMBRE_CAP",
  "CANT_USOS",
  "CANT_ACIERTOS",
  "CANT_FALLOS",
  "ULTIMA_FECHA",
  "IDET",
  "DECIM",
  "CARACTER",
  "REDIRECT"
  };
}

