
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symTI {
  /* terminals */
  public static final int IDETIQUETA = 33;
  public static final int MULT = 45;
  public static final int WIDTH = 39;
  public static final int VALP = 48;
  public static final int TEXTAREA = 16;
  public static final int INPUT = 15;
  public static final int RESTA = 44;
  public static final int ONCLICK = 42;
  public static final int ROWS = 36;
  public static final int PUNTCOMA = 61;
  public static final int AND = 58;
  public static final int IGUAL = 8;
  public static final int OPTION = 18;
  public static final int DECIM = 50;
  public static final int TYPE = 32;
  public static final int OR = 57;
  public static final int PALABRAS = 47;
  public static final int FINVARIABLESCRIP = 52;
  public static final int FSIZE = 29;
  public static final int CLASS = 37;
  public static final int CORCHCUADI = 6;
  public static final int DIV = 19;
  public static final int SUMA = 43;
  public static final int SCRIPTING = 25;
  public static final int SELECT = 17;
  public static final int CORCHCUADD = 7;
  public static final int EXCL = 4;
  public static final int EOF = 0;
  public static final int LINK = 12;
  public static final int PALABRA = 46;
  public static final int error = 1;
  public static final int COMA = 64;
  public static final int VARIABLESCRIP = 51;
  public static final int CORCHI = 62;
  public static final int BR = 21;
  public static final int HEIGHT = 40;
  public static final int CORCHD = 63;
  public static final int HEAD = 10;
  public static final int NAME = 34;
  public static final int MENIG = 53;
  public static final int COLOR = 28;
  public static final int PAR = 24;
  public static final int IMG = 20;
  public static final int COLS = 35;
  public static final int BARRA = 5;
  public static final int IDET = 49;
  public static final int TEXTALIGN = 31;
  public static final int TITLE = 11;
  public static final int MAYIG = 54;
  public static final int MEN = 3;
  public static final int PARI = 59;
  public static final int ALT = 41;
  public static final int SPAM = 14;
  public static final int HREF = 26;
  public static final int BODY = 13;
  public static final int PARD = 60;
  public static final int GCIC = 9;
  public static final int DIFER = 56;
  public static final int DOBIGUAL = 55;
  public static final int DOSPUNT = 65;
  public static final int BACK = 27;
  public static final int FFAMILY = 30;
  public static final int SRC = 38;
  public static final int MAY = 2;
  public static final int BUTTON = 22;
  public static final int H1 = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAY",
  "MEN",
  "EXCL",
  "BARRA",
  "CORCHCUADI",
  "CORCHCUADD",
  "IGUAL",
  "GCIC",
  "HEAD",
  "TITLE",
  "LINK",
  "BODY",
  "SPAM",
  "INPUT",
  "TEXTAREA",
  "SELECT",
  "OPTION",
  "DIV",
  "IMG",
  "BR",
  "BUTTON",
  "H1",
  "PAR",
  "SCRIPTING",
  "HREF",
  "BACK",
  "COLOR",
  "FSIZE",
  "FFAMILY",
  "TEXTALIGN",
  "TYPE",
  "IDETIQUETA",
  "NAME",
  "COLS",
  "ROWS",
  "CLASS",
  "SRC",
  "WIDTH",
  "HEIGHT",
  "ALT",
  "ONCLICK",
  "SUMA",
  "RESTA",
  "MULT",
  "PALABRA",
  "PALABRAS",
  "VALP",
  "IDET",
  "DECIM",
  "VARIABLESCRIP",
  "FINVARIABLESCRIP",
  "MENIG",
  "MAYIG",
  "DOBIGUAL",
  "DIFER",
  "OR",
  "AND",
  "PARI",
  "PARD",
  "PUNTCOMA",
  "CORCHI",
  "CORCHD",
  "COMA",
  "DOSPUNT"
  };
}

