
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symU {
  /* terminals */
  public static final int NOMBRE_CAP = 7;
  public static final int DATOS_FORM = 12;
  public static final int CANT_ACIERTOS = 9;
  public static final int ID_CAP = 6;
  public static final int MAY = 2;
  public static final int MEN = 3;
  public static final int EOF = 0;
  public static final int CANT_FALLOS = 10;
  public static final int error = 1;
  public static final int ULTIMA_FECHA = 11;
  public static final int BARRA = 4;
  public static final int VALP = 5;
  public static final int CANT_USOS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAY",
  "MEN",
  "BARRA",
  "VALP",
  "ID_CAP",
  "NOMBRE_CAP",
  "CANT_USOS",
  "CANT_ACIERTOS",
  "CANT_FALLOS",
  "ULTIMA_FECHA",
  "DATOS_FORM"
  };
}

