
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symG {
  /* terminals */
  public static final int error = 1;
  public static final int GCIC = 5;
  public static final int EXCL = 4;
  public static final int MEN = 3;
  public static final int BACK = 6;
  public static final int MAY = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAY",
  "MEN",
  "EXCL",
  "GCIC",
  "BACK"
  };
}

